### PR TITLE
Allow version catalogs to include aliases from nested catalogs

### PR DESCRIPTION
**Pull request by melix**
Our BOM plugin lets us declare which BOMs should be imported, via
the `boms.` property prefix in the `libs.versions.toml` file. For
example:

```toml
boms-micronaut-gcp = {
    module = "io.micronaut.gcp:micronaut-gcp-bom",
    version.ref = "managed-micronaut-gcp"
}
```

would trigger the creation of a BOM which dependency
management section _imports_ the gcp BOM. However, if
we move from entries which were previously declared
in the catalog, and are now defined in the imported
BOM, we have a problem. For example, if the catalog
used to contain this:

```toml
managed-micronaut-gcp = {
    module = "io.micronaut.gcp:micronaut-gcp-function",
    version.ref = "managed-micronaut-gcp"
}
```

and that we remove the entry because we're moving
to importing the BOM via `boms.`, then it's a breaking
change for users, who wouldn't be able to use the notation:

```gradle
dependencies {
   implementation(mn.micronaut.gcp.function)
```

in their build files, because that entry would be removed.

This commit fixes the problem by introducing an _inlining_
mechanism. Basically, the idea is that when we import a BOM,
we try to see if it's published with a version catalog
(which is the case for the Micronaut BOMs). If so, then we
_inline_ the entries of the imported catalog into the current
one, without declaring a version.

The net result, in the example above, is that the alias is
effectively still present in the Micronaut BOM, so users
can continue to use the alias as before. Of course, this only
works if, and only if, the aliases of the nested catalog are
actually the same as the removed ones. From my tests, this
looks to be often the case. A noticeable difference is that
for `mn.micronaut.gcp` you'd have to use `mn.micronaut.gcp.common`
instead (because of that alias difference). This is still
a breaking change, but a reasonable tradeoff.

If the imported BOM is actually an external project BOM without a catalog, like, say, the jackson BOM, 
then we don't do anything and don't add entries to the catalog
automatically. If the external BOM is published with a catalog, then we
would also inline its entries. There's a property which allows filtering
out aliases to inline, and another to completely disable inlining.

See https://github.com/micronaut-projects/micronaut-core/pull/6987

### CODE REVIEW

**Review by timyates — APPROVED** [review]
LGTM 👍 

Quick question, what happens if say 2 boms define the same managed library?

Can that be detected?  And if it can, can it be made to fail the build?

**Review by graemerocher — APPROVED** [review]

**Comment by melix** [comment]
> Quick question, what happens if say 2 boms define the same managed library?

Currently, first wins.

> Can that be detected? And if it can, can it be made to fail the build?

It is already detected, but not logged. I can add logging to make it clear that there's a conflict. Failing the build is not necessarily a good option since there aren't many workarounds in that case.

**Comment by timyates** [comment]
Logging it would be good 👍. My concern is someone adds a new managed library to a module, and shadows the name of an existing one by mistake, we wouldn't know and triaging might be a nightmare 🤔. Could we have a verify task that verifies this isn't happening?

This is awesome btw 👍

**Comment by melix** [comment]
> and shadows the name of an existing one by mistake

I added logging. I can make the build fail, but the idea was that if the catalog itself declares an alias with the same name, it takes precedence over any inlined one. Now you'd also get a warning if this happens, in which case you'd add the alias to the exclude list to get rid of the warning.

**Comment by timyates** [comment]
Awesome 👍

Fingers crossed we don't see any warnings when this is applied to the current build 😉🤞

**Comment by melix** [comment]
> Fingers crossed we don't see any warnings when this is applied to the current build

There isn't, I tested the whole thing with `micronaut-core`, `3.3.x`

**Pull request merged**
