### PR TITLE
Add managed plugins to the generated catalog

### PR DESCRIPTION
**Pull request by timyates**
This PR adds the ability to "_manage_" plugins (as we do for versions and libraries)

This should mean we can manage the ksp plugin in the Micronaut Core catalog, and then use this managed version in consuming builds with `alias(mn.plugins.ksp)`

As in the test, the following:

```
[versions]
managed-ksp = "1.9.22-1.0.17"

[plugins]
managed-ksp = { id = "com.google.devtools.ksp", version.ref = "managed-ksp" }
managed-hard-versioned = { id = "some.other.id", version = "1.2.3" }
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }
```

will results in a catalog containing

```
[versions]
ksp = "1.9.22-1.0.17"

[plugins]
hard-versioned = {id = "some.other.id", version = "1.2.3" }
ksp = {id = "com.google.devtools.ksp", version.ref = "ksp" }
```

As you can see, it's possible to hard-code a version instead of using a reference.  I believe this makes sense, as the ksp version above ends up in the pom as a property, but this doesn't make much sense for Gradle plugins...

I wonder if it's worth inlining versions for plugins for this reason... @melix what do you think?

### CODE REVIEW

**Review by melix — APPROVED** [review]
Great work! I think we shouldn't inline versions in the `plugins` block. Especially it's possible in Gradle to override the version when importing a catalog, so it would make sense to keep the version reference, even if it appears in the pom file.

I think we'll also need to update the `micronaut-platform` project to inline plugin definitions too now.

**Comment by timyates** [comment]
> I think we'll also need to update the `micronaut-platform` project to inline plugin definitions too now.

Cool, I'll take a look :-)

**Comment by timyates** [comment]
Putting this back to a draft until I check (and fix) the platform, and check it actually works

**Comment by melix** [comment]
> @melix should we allow inline versions?

I would be tempted to disallow them, but no strong opinion.

> Anyway, I think this works for the micronaut-platform merging now.... I have been trying to find or think of a way of testing it, but I've failed... Is there an existing test?

No, usually I do this by using an includeBuild in the platform settings.gradle

**Review by sdelamo — APPROVED** [review]

**Comment by timyates** [comment]
> No, usually I do this by using an includeBuild in the platform settings.gradle

I've done manual tests with my usual `mavenLocal` malarkey, but it would be good to get another pair of eyes checking it functionally 😄

**Comment by timyates** [comment]
@melix ping!

> I've done manual tests with my usual mavenLocal malarkey, but it would be good to get another pair of eyes checking it functionally 😄

**Review by melix — APPROVED** [review]
Checked locally with micronaut platform too :+1:

**Pull request merged**
