### PR TITLE
Add a `[configuration]` macro for properties

### LINKED ISSUE #438: Add configuration macro for showing either Properties file or YAML or TOML etc. snippets
Since we are moving to properties files by default for Micronaut 4 it is critical that all configuration file snippets show both Java properties and YAML config in a tab based snippet preview similar to our Gradle/Maven switcher. 

It would be nice to be implement do something like:

```
[.configuration]
----
foo.bar=test
foo.baz=stuff
----
```

Will need a tree processor https://docs.asciidoctor.org/asciidoctorj/latest/extensions/treeprocessor/

### PR DESCRIPTION
**Pull request by melix**
This commit introduces a `[configuration]` macro which generates Micronaut configuration in several configuration languages, based on a single notation (YAML).

For example, writing:

```
.Configuring Ribbon
[configuration]
----
ribbon:
  VipAddress: test
  ServerListRefreshInterval: 2000
----
````

This would automatically generate a multi-tab code sample with the YAML, TOML, Hocon. Groovy and properties configuration formats.

It should be possible, in a majority of cases, to replace:

```
[source,yaml]
```

with

```
[configuration]
```

However, be careful: sometimes the surrounding text contains sentences like "the following application.yml file" or similar.
In addition, it is recommended to remove callouts and comments, as they would only appear in the YAML version.

Fixes #438

### CODE REVIEW

**Comment by melix** [comment]
Here is a rendered version of the Micronaut Core docs converted to use this:

[docs.zip](https://github.com/micronaut-projects/micronaut-build/files/10414330/docs.zip)

**Comment by melix** [comment]
I am _absolutely_ not sure that the `properties` format correctly handles this:

```
logger:
  levels:
    ROOT: INFO
    io.github.jhipster.sample: INFO
    io.github.jhipster: INFO
```

for now I'm generating:

```
logger.levels.ROOT=INFO
logger.levels.io\\.github\\.jhipster\\.sample=INFO
logger.levels.io\\.github\\.jhipster=INFO
```

But I am not sure that this is the right format.

**Comment by sdelamo** [comment]
can we target this PR to 5.3.x ?

**Comment by melix** [comment]
Technically speaking it's a new feature with dependency upgrades, so it shouldn't target 5.3.x. I can target a 5.4.x, but I need to change the code so that it builds with Java 8.

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
> Technically speaking it's a new feature with dependency upgrades, so it shouldn't target 5.3.x. I can target a 5.4.x, but I need to change the code so that it builds with Java 8.

yes, 5.4.x would be great. It would be good if we could be applying this to MN 3.x versions of the modules.

**Comment by graemerocher** [comment]
oh, I don't think the back ticks are needed are they?

**Comment by melix** [comment]
That's the whole question, I have no idea how this is mapped internally: how does it make the difference between a bean property and the logger names? It seems it works OOTB with Groovy, but I have no clue how we do this for properties.

**Comment by graemerocher** [comment]
should just be flattened:

```
logger.levels.ROOT=INFO
logger.levels.io.github.jhipster.sample=INFO
logger.levels.io.github.jhipster=INFO
```

**Comment by graemerocher** [comment]
to explain how it works it uses `getProperties("logger.levels", RAW)` https://github.com/micronaut-projects/micronaut-core/blob/4d06ae7a3ac21beaa4b28f103779f9c622abf644/context/src/main/java/io/micronaut/logging/PropertiesLoggingLevelsConfigurer.java#L88

Which will return a map of the raw keys (no normalization, just what the user input) to values below the `log.levels` prefix.

**Comment by graemerocher** [comment]
Ultimately whatever the user uses (YAML, TOML, properties, Groovy) everything gets flattened into a map of key value pairs

**Pull request merged**
