### PR TITLE
add Gradle wrapper validation to workflow

### PR DESCRIPTION
**Pull request by sullis**
https://github.com/gradle/wrapper-validation-action
﻿

### CODE REVIEW

**Comment by ilopmar** [comment]
Hey, thanks for the PR. I honesty don't see this adds too much value. We are the ones that update the Gradle Wrapper and we don't even do it manually but it's automated from a "template" repository and then propagated to the rest of the repositories.

Anyone has other thoughts?

**Comment by ilopmar** [comment]
Thanks @alvarosanchez, I wasn't aware we were already using this in the other projects. I'm ok then with doing it here in the `release` workflow.

@sullis Can you please update the PR to add this only to the release workflow as Alvaro suggested?

**Comment by sullis** [comment]
> @sullis Can you please update the PR to add this only to the release workflow as Alvaro suggested?

Done.

**Review by ilopmar — APPROVED** [review]

**Comment by ilopmar** [comment]
Thanks for the contribution!

**Pull request merged**
