### PR TITLE
Allow to publish modules with name containing `adoc` words

### PR DESCRIPTION
**Pull request by altro3**

### CODE REVIEW

**Comment by altro3** [comment]
@graemerocher @melix please merge this fix and publish new releae. Can't run publish task with new module openapi-adoc :-(

**Review by melix — APPROVED** [review]
We really need to get rid of that dirty logic. But for now this will do :)

**Comment by altro3** [comment]
@melix hi! whe you plan merge and release this fix? Need it for this: https://github.com/micronaut-projects/micronaut-openapi/pull/1233

**Comment by melix** [comment]
Release 6.5.7 is out with the fix, thanks!

**Pull request merged**
